# Generated by Django 5.1.2 on 2024-10-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='articles', verbose_name='Фото'),
        ),
    ]
