# Generated by Django 5.1.2 on 2024-10-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_photos_delete_articlephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.CharField(max_length=250, null=True, verbose_name='Введение'),
        ),
    ]
