# Generated by Django 5.1.2 on 2024-10-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_intro'),
        ('services', '0009_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='specialities',
            field=models.ManyToManyField(null=True, related_name='articles', to='services.speciality', verbose_name='Теги'),
        ),
    ]
