# Generated by Django 5.1.2 on 2024-10-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_specialities'),
        ('services', '0010_speciality_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='specialities',
            field=models.ManyToManyField(related_name='articles', to='services.speciality', verbose_name='Теги'),
        ),
    ]
