# Generated by Django 5.1.2 on 2024-10-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_specialities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(max_length=250, null=True, verbose_name='Введение'),
        ),
    ]
