version: '3.8'

services:
  redis:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: your_password
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - "6379:6379"
    networks:
      - dev
    
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - db
      - backend 
      - redis
    networks:
      - dev

  db:
    image: postgres:15-alpine
    container_name: db
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  backend: 
    build: . 
    entrypoint: /entrypoint.sh
    ports: 
      - "8000:8000"
      - "5555:5555"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./media:/media
    networks:
      - dev

networks:
  dev: