# Generated by Django 5.1.2 on 2024-10-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_servicetype_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='duration',
            field=models.SmallIntegerField(default=60, verbose_name='Длительность'),
        ),
    ]
