# Generated by Django 5.1.2 on 2024-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_servicetype_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
