# Generated by Django 5.1.2 on 2024-10-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_alter_servicetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='duration',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Длительность'),
        ),
    ]
