# Generated by Django 5.1.2 on 2024-11-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_alter_servicetype_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='duration',
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Цена'),
        ),
    ]
