# Generated by Django 5.1.2 on 2024-11-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_alter_servicetype_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='is_displayed',
            field=models.BooleanField(default=True, verbose_name='Отображается в общем списке'),
        ),
    ]
