# Generated by Django 5.1.2 on 2024-11-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_servicetype_is_displayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Прайс-лист')),
            ],
        ),
    ]
