# Generated by Django 5.1.2 on 2024-11-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0010_pricepdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricepdf',
            options={'verbose_name': 'Прайс-лист', 'verbose_name_plural': 'Прайс-лист'},
        ),
        migrations.AlterField(
            model_name='pricepdf',
            name='file',
            field=models.FileField(upload_to='prices', verbose_name='Прайс-лист'),
        ),
    ]
