# Generated by Django 5.1.2 on 2025-01-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0011_alter_pricepdf_options_alter_pricepdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['pk'], 'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
        # migrations.AddField(
        #     model_name='pricepdf',
        #     name='title',
        #     field=models.TextField(default='Прайс-лист', help_text='Название вкладки в админ. панели', verbose_name='Прайс-лист'),
        # ),
        # migrations.AddField(
        #     model_name='servicetype',
        #     name='booking_link',
        #     field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на запись'),
        # ),
        migrations.AlterField(
            model_name='servicetype',
            name='booking_link',
            field=models.CharField(max_length=500, blank=True, null=True, verbose_name='Ссылка на запись'),
        ),
    ]
