# Generated by Django 5.1.2 on 2024-11-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0011_alter_pricepdf_options_alter_pricepdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='booking_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на запись'),
        ),
    ]
