# Generated by Django 5.1.2 on 2024-11-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0012_servicetype_booking_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='booking_link',
        ),
    ]
