# Generated by Django 5.1.2 on 2024-10-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_imagemodel_alter_article_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
        migrations.AddField(
            model_name='article',
            name='photos',
            field=models.ManyToManyField(blank=True, to='landing.imagemodel', verbose_name='Фотографии'),
        ),
    ]
