# Generated by Django 5.1.2 on 2024-10-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_remove_article_photo_article_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='Photo',
        ),
    ]
