# Generated by Django 5.1.2 on 2024-10-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_rename_imagemodel_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
