# Generated by Django 5.1.2 on 2024-10-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_rename_photo_articlephoto_alter_articlephoto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
