# Generated by Django 5.1.2 on 2024-10-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_remove_doctor_branch'),
        ('landing', '0014_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
