# Generated by Django 5.1.2 on 2024-10-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_delete_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Открыта'),
        ),
    ]
