# Generated by Django 5.1.2 on 2024-10-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_alter_question_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Открыта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
