# Generated by Django 5.1.2 on 2024-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_alter_question_email_alter_question_is_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_open',
        ),
        migrations.AddField(
            model_name='question',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AddField(
            model_name='request',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
