# Generated by Django 5.1.2 on 2024-11-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_licensepage_delete_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensepage',
            options={'verbose_name': 'Страница лицензии', 'verbose_name_plural': 'Страницы лицензии'},
        ),
        migrations.AlterField(
            model_name='licensepage',
            name='file',
            field=models.FileField(upload_to='license/', verbose_name='Страница'),
        ),
    ]
