# Generated by Django 5.1.2 on 2024-11-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контактные данные', 'verbose_name_plural': 'Контактные данные'},
        ),
    ]
