# Generated by Django 5.1.2 on 2024-11-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_alter_contactinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuridicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgainzation_full_name', models.CharField(max_length=120, verbose_name='Полное наименование медицинской организации')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес юридического лица')),
                ('ogrn', models.SmallIntegerField(max_length=13, verbose_name='ОГРН')),
                ('registered_authority_name', models.CharField(max_length=200, verbose_name='Наименование зарегистрировавшего органа')),
                ('registering_date', models.CharField(max_length=50, verbose_name='Дата государственной регистрации')),
                ('inn', models.SmallIntegerField(max_length=10, verbose_name='ИНН')),
                ('founders_info', models.TextField(verbose_name='Сведения об учредителях')),
                ('license_info', models.TextField(verbose_name='Сведения о лицензии на осуществление медицинской деятельности')),
                ('title', models.TextField(default='Юридическая информация', help_text='Название вкладки в админ. панели', verbose_name='Юридическая информация')),
            ],
            options={
                'verbose_name': 'Юридическая информация',
                'verbose_name_plural': 'Юридическая информация',
            },
        ),
    ]
