# Generated by Django 5.1.2 on 2024-11-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_juridicalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridicalinfo',
            name='inn',
            field=models.SmallIntegerField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='juridicalinfo',
            name='ogrn',
            field=models.SmallIntegerField(verbose_name='ОГРН'),
        ),
    ]
