# Generated by Django 5.1.2 on 2024-11-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_alter_juridicalinfo_inn_alter_juridicalinfo_ogrn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingDataAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prices', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Согласие на обработку персональных данных',
                'verbose_name_plural': 'Согласие на обработку персональных данных',
            },
        ),
    ]
