# Generated by Django 5.1.2 on 2024-11-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_processingdataagreement_title_useragreementpdf_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridicalinfo',
            name='inn',
            field=models.CharField(max_length=10, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='juridicalinfo',
            name='ogrn',
            field=models.CharField(max_length=13, verbose_name='ОГРН'),
        ),
    ]
