# Generated by Django 5.1.2 on 2024-11-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_alter_juridicalinfo_inn_alter_juridicalinfo_ogrn'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес филиала')),
                ('work_mode', models.TextField(verbose_name='Режим работы')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.contactinfo', verbose_name='Контактная информация')),
            ],
        ),
    ]
