# Generated by Django 5.1.2 on 2024-11-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_filialinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filialinfo',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
    ]
