# Generated by Django 5.1.2 on 2024-11-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0031_alter_filialinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialinfo',
            name='phone',
            field=models.CharField(default='', max_length=18, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
