# Generated by Django 5.1.2 on 2024-11-26 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0032_filialinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filialinfo',
            name='contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filials', to='landing.contactinfo', verbose_name='Контактная информация'),
        ),
    ]
