# Generated by Django 5.1.2 on 2024-11-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0033_alter_filialinfo_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialinfo',
            name='solid_phone',
            field=models.CharField(default='', max_length=11, verbose_name='Номер телефона (только цифры и "+")'),
            preserve_default=False,
        ),
    ]
