# Generated by Django 5.1.2 on 2024-10-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_speciality_slug'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctors.speciality', verbose_name='Специализация'),
        ),
    ]
