# Generated by Django 5.1.2 on 2024-10-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicetype_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Фото специализации',
                'verbose_name_plural': 'Фото специализации',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.FileField(null=True, upload_to='specialities', verbose_name='Иконка')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('photos', models.ManyToManyField(blank=True, to='services.specialityphoto', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
