# Generated by Django 5.1.2 on 2024-10-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_symptom_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='photos',
        ),
        migrations.AddField(
            model_name='specialityphoto',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.speciality', verbose_name='Специализация'),
        ),
    ]
