# Generated by Django 5.1.2 on 2024-10-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_speciality_photos_specialityphoto_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialityphoto',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.speciality', verbose_name='Специализация'),
        ),
    ]
