# Generated by Django 5.1.2 on 2024-10-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_speciality_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='is_displayed',
            field=models.TextField(default=True, verbose_name='Отображается ли на главной странице'),
        ),
    ]
