# Generated by Django 5.1.2 on 2024-10-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_speciality_is_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='is_displayed',
            field=models.BooleanField(default=True, verbose_name='Отображается ли на главной странице'),
        ),
    ]
