# Generated by Django 5.1.2 on 2024-10-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_speciality_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialityphoto',
            options={'ordering': ['pk'], 'verbose_name': 'Фото специализации', 'verbose_name_plural': 'Фото специализации'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['pk'], 'verbose_name': 'Симптом', 'verbose_name_plural': 'Симптомы'},
        ),
    ]
