# Generated by Django 5.1.2 on 2025-01-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_specialityphoto_options_alter_symptom_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='is_displayed',
            new_name='is_displayed_on_homepage',
        ),
    ]
