# Generated by Django 5.1.2 on 2025-01-30 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('resume', models.FileField(upload_to='vacancies/replies/', verbose_name='Резюме')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(default='', max_length=500, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
