# Generated by Django 5.1.2 on 2025-01-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancyreply_vacancy_created_at_vacancy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyreply',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='vacancies/replies/', verbose_name='Резюме'),
        ),
    ]
