# Generated by Django 5.1.2 on 2024-10-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_branch_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='specialities',
        ),
    ]
