# Generated by Django 5.1.2 on 2024-10-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['name'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(default=' ', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
