# Generated by Django 5.1.2 on 2024-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_speciality_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.FileField(null=True, upload_to='doctors', verbose_name='Фото'),
        ),
    ]
