# Generated by Django 5.1.2 on 2024-10-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_doctor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Фото специализации',
                'verbose_name_plural': 'Фото специализации',
            },
        ),
        migrations.AddField(
            model_name='speciality',
            name='photos',
            field=models.ManyToManyField(blank=True, to='doctors.specialityphoto', verbose_name='Фотографии'),
        ),
    ]
