# Generated by Django 5.1.2 on 2024-10-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_alter_doctor_branch_remove_speciality_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
    ]
