# Generated by Django 5.1.2 on 2024-10-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_remove_doctor_email_remove_doctor_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='branch',
        ),
    ]
