# Generated by Django 5.1.2 on 2024-10-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_remove_doctor_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patronymic',
            field=models.CharField(default=' ', max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
