# Generated by Django 5.1.2 on 2024-10-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_alter_doctor_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='prodoctorov_profile',
            field=models.TextField(default=' ', verbose_name='Профиль в ПроДокторов'),
            preserve_default=False,
        ),
    ]
