# Generated by Django 5.1.2 on 2024-10-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_doctor_prodoctorov_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='prodoctorov_profile',
            field=models.TextField(verbose_name='Ссылка на профиль в ПроДокторов'),
        ),
    ]
