# Generated by Django 5.1.2 on 2024-10-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_alter_doctor_prodoctorov_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Слаг'),
        ),
    ]
