# Generated by Django 5.1.2 on 2024-10-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_doctor_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['pk'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
    ]
