# Generated by Django 5.1.2 on 2024-11-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0024_doctor_display_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['display_priority'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
    ]
